### ISSUE TITLE
Plugin fail to start

### ISSUE THREAD

**Issue by Ichinistes14** [VitaliyMubarakov/ServersMenuExtender#10]
When loadingthe plugin, it say :
![image](https://github.com/VitaliyMubarakov/ServersMenuExtender/assets/141771041/e5d6e6cd-6de3-494a-85d6-3e776278b25f)
And there are the error give in the console :
![image](https://github.com/VitaliyMubarakov/ServersMenuExtender/assets/141771041/6f07ed6a-c968-48da-9162-896a70bd7515)

**Comment by mayman007** [comment]
Same issue

**Comment by Naiizey** [comment]
I've just requested a pull from a fork I made were I've fixed the problem. Feel free to take from it !
