### ISSUE TITLE
Save Collapsed Folder State + Re-collapse after opening Search. 

### ISSUE THREAD

**Issue by Mx772** [VitaliyMubarakov/ServersMenuExtender#2]
Currently if you have folders with severs inside of them, clicking the 'search' will expand them all. (Which I like, and think is expected)

That being said, after closing the search, the servers stay expanded. 

It looks like the server items are stored as a `listItem-xyz` and folders are stored as `wrapper-xyz` div classes.
It should be possible to store/restore which folders are collapsed after clicking out of the search action.

**Comment by VitaliyMubarakov** [comment]
This is my solution to the problem with remembering servers and their names in folders, probably solve in the future.

**Comment by VitaliyMubarakov** [comment]
fixed
